"""Add routing_rules table and tasks.assigned_role (TE-02)

Revision ID: 9d80e1ea1f1f
Revises: d5a6e6feba43
Create Date: 2026-09-15 18:13:43.756297

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9d80e1ea1f1f'
down_revision: str | None = 'd5a6e6feba43'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('default_role', sa.String(length=20), nullable=False),
    sa.Column('escalate_after_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_rules_task_type'), 'routing_rules', ['task_type'], unique=True)
    op.add_column('tasks', sa.Column('assigned_role', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_tasks_assigned_role'), 'tasks', ['assigned_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_assigned_role'), table_name='tasks')
    op.drop_column('tasks', 'assigned_role')
    op.drop_index(op.f('ix_routing_rules_task_type'), table_name='routing_rules')
    op.drop_table('routing_rules')
    # ### end Alembic commands ###
