"""initial core schema

Revision ID: d5a6e6feba43
Revises: 
Create Date: 2026-08-22 03:02:46.149727

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd5a6e6feba43'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('primary_contact', sa.String(length=255), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('books_system', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('practice_id', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('books_system', sa.String(length=20), nullable=False),
    sa.Column('tally_company_name', sa.String(length=255), nullable=True),
    sa.Column('tally_connection_path', sa.String(length=20), nullable=True),
    sa.Column('zoho_organization_id', sa.String(length=100), nullable=True),
    sa.Column('zoho_oauth_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_health', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('dropbox_path', sa.String(length=500), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_sender_maps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('sender_domain', sa.String(length=255), nullable=True),
    sa.Column('sender_address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('linked_record_type', sa.String(length=50), nullable=True),
    sa.Column('linked_record_id', sa.String(length=36), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('created_by_agent', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_table('vendor_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('vendor_name_raw', sa.String(length=255), nullable=False),
    sa.Column('tally_ledger_name', sa.String(length=255), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('hsn_code', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('vouchers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('extracted_data_id', sa.String(), nullable=True),
    sa.Column('books_connection_id', sa.String(), nullable=True),
    sa.Column('posting_system', sa.String(length=20), nullable=True),
    sa.Column('voucher_type', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cgst', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sgst', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('igst', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vendor_gstin', sa.String(length=15), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['books_connection_id'], ['books_connections.id'], ),
    sa.ForeignKeyConstraint(['extracted_data_id'], ['extracted_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vouchers')
    op.drop_table('extracted_data')
    op.drop_table('vendor_mappings')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('email_sender_maps')
    op.drop_table('documents')
    op.drop_table('books_connections')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('clients')
    # ### end Alembic commands ###
